// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userPublishMapFieldNames          = builder.RawFieldNames(&UserPublishMap{})
	userPublishMapRows                = strings.Join(userPublishMapFieldNames, ",")
	userPublishMapRowsExpectAutoSet   = strings.Join(stringx.Remove(userPublishMapFieldNames, "`publish_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), ",")
	userPublishMapRowsWithPlaceHolder = strings.Join(stringx.Remove(userPublishMapFieldNames, "`publish_id`", "`create_time`", "`update_time`", "`create_at`", "`update_at`"), "=?,") + "=?"

	cacheUserPublishMapPublishIdPrefix     = "cache:userPublishMap:publishId:"
	cacheUserPublishMapUserIdVideoIdPrefix = "cache:userPublishMap:userId:videoId:"
	cacheUserPuslishMapUserIdVideosPrefix  = "cache:userPublishMap:userId:videoIds:"
)

type (
	userPublishMapModel interface {
		Insert(ctx context.Context, data *UserPublishMap) (sql.Result, error)
		FindOne(ctx context.Context, publishId int64) (*UserPublishMap, error)
		FindMany(ctx context.Context, userId int64) ([]*UserPublishMap, error)
		FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*UserPublishMap, error)
		Update(ctx context.Context, data *UserPublishMap) error
		Delete(ctx context.Context, publishId int64) error
	}

	defaultUserPublishMapModel struct {
		sqlc.CachedConn
		table string
	}

	UserPublishMap struct {
		PublishId  int64     `db:"publish_id"`  // ID
		UserId     int64     `db:"user_id"`     // 用户id
		VideoId    int64     `db:"video_id"`    // 视频id
		CreateTime time.Time `db:"create_time"` // 创建时间
		UpdateTime time.Time `db:"update_time"` // 更新时间
	}
)

func newUserPublishMapModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultUserPublishMapModel {
	return &defaultUserPublishMapModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`user_publish_map`",
	}
}

func (m *defaultUserPublishMapModel) Delete(ctx context.Context, publishId int64) error {
	data, err := m.FindOne(ctx, publishId)
	if err != nil {
		return err
	}

	userPublishMapPublishIdKey := fmt.Sprintf("%s%v", cacheUserPublishMapPublishIdPrefix, publishId)
	userPublishMapUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheUserPublishMapUserIdVideoIdPrefix, data.UserId, data.VideoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `publish_id` = ?", m.table)
		return conn.ExecCtx(ctx, query, publishId)
	}, userPublishMapPublishIdKey, userPublishMapUserIdVideoIdKey)
	return err
}

func (m *defaultUserPublishMapModel) FindOne(ctx context.Context, publishId int64) (*UserPublishMap, error) {
	userPublishMapPublishIdKey := fmt.Sprintf("%s%v", cacheUserPublishMapPublishIdPrefix, publishId)
	var resp UserPublishMap
	err := m.QueryRowCtx(ctx, &resp, userPublishMapPublishIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `publish_id` = ? limit 1", userPublishMapRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, publishId)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPublishMapModel) FindMany(ctx context.Context, userId int64) ([]*UserPublishMap, error) {
	userPublishUseridVideosKey := fmt.Sprintf("%s%v", cacheUserPuslishMapUserIdVideosPrefix, userId)
	var resp []*UserPublishMap
	err := m.QueryRowCtx(ctx, &resp, userPublishUseridVideosKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `user_id` = ?", userPublishMapRows, m.table)
		return conn.QueryRowsCtx(ctx, v, query, userId)
	})
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPublishMapModel) FindOneByUserIdVideoId(ctx context.Context, userId int64, videoId int64) (*UserPublishMap, error) {
	userPublishMapUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheUserPublishMapUserIdVideoIdPrefix, userId, videoId)
	var resp UserPublishMap
	err := m.QueryRowIndexCtx(ctx, &resp, userPublishMapUserIdVideoIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `video_id` = ? limit 1", userPublishMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, videoId); err != nil {
			return nil, err
		}
		return resp.PublishId, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserPublishMapModel) Insert(ctx context.Context, data *UserPublishMap) (sql.Result, error) {
	userPublishMapPublishIdKey := fmt.Sprintf("%s%v", cacheUserPublishMapPublishIdPrefix, data.PublishId)
	userPublishMapUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheUserPublishMapUserIdVideoIdPrefix, data.UserId, data.VideoId)
	userPublishUseridVideosKey := fmt.Sprintf("%s%v", cacheUserPuslishMapUserIdVideosPrefix, data.UserId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, userPublishMapRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.VideoId)
	}, userPublishMapPublishIdKey, userPublishMapUserIdVideoIdKey, userPublishUseridVideosKey)
	return ret, err
}

func (m *defaultUserPublishMapModel) Update(ctx context.Context, newData *UserPublishMap) error {
	data, err := m.FindOne(ctx, newData.PublishId)
	if err != nil {
		return err
	}

	userPublishMapPublishIdKey := fmt.Sprintf("%s%v", cacheUserPublishMapPublishIdPrefix, data.PublishId)
	userPublishMapUserIdVideoIdKey := fmt.Sprintf("%s%v:%v", cacheUserPublishMapUserIdVideoIdPrefix, data.UserId, data.VideoId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `publish_id` = ?", m.table, userPublishMapRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.VideoId, newData.PublishId)
	}, userPublishMapPublishIdKey, userPublishMapUserIdVideoIdKey)
	return err
}

func (m *defaultUserPublishMapModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheUserPublishMapPublishIdPrefix, primary)
}

func (m *defaultUserPublishMapModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `publish_id` = ? limit 1", userPublishMapRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultUserPublishMapModel) tableName() string {
	return m.table
}
